name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2019.4.9f1-android-0.12.0
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - run: pip install yadisk

        - run: python upload.py
