name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    container: python
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - uses: actions/setup-python@v2
          with:
            python-version: '3.6'
        - run: python pip install yadisk
        - run: python upload.py
